AllCops:
  TargetRubyVersion: 2.4
  SuggestExtensions: false
  NewCops: enable
  Exclude:
    - '**/Vagrantfile'
    - 'examples/**/*'
    - 'vendor/**/*'
    - 'Gemfile'

Metrics/AbcSize:
  Max: 18

Metrics/ClassLength:
  Max: 120

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 12

Metrics/ModuleLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
